import Banner from "@/components/Banner";
import Products from "@/components/Products";
import { Product } from "@/type";
import Head from "next/head";

type ProductPropsType = {
  productData: Product;
};

export default function Home({ productData }: ProductPropsType) {
  return (
    <>
      <Head>
        <title>Shoppers App | By Arioglu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-lightBlue">
        <div className="max-w-contentContainer mx-auto bg-white">
          <Banner />
          <Products productData={productData} />
        </div>
      </main>
    </>
  );
}

// ================ SSR data fetching start here ===================

export const getServerSideProps = async () => {
  const response = await fetch("http://localhost:3000/api/productdata");
  const productData = await response.json();

  return {
    props: { productData },
  };
};
